name: build

on:
  push:
    branches:
    - '**'
    paths-ignore:
      - '**.md'
      - '.**'
      - 'LICENSE'
  pull_request:
    branches:
    - '**'
    paths-ignore:
      - '**.md'
      - '.**'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
